### ISSUE TITLE
Entrypoint script should exec to Junebug process

### ISSUE THREAD

**Issue by JayH5** [praekeltfoundation/docker-junebug#3]
``` bash
exec jb [OPTIONS...]
```

The Junebug process should take over from the Bash script one as the Bash process is unneeded and will block signals to the Junebug process.

**Comment by jerith** [comment]
If we're using `dinit`, the signals should go to the whole process group instead of just the top process. That said, a script that exists only to run another (single) process should still `exec` at the end.

**Comment by hodgestar** [comment]
Addressed in #2.
