### ISSUE TITLE
Install pre-built version of yowsup

### ISSUE THREAD

**Issue by JayH5** [praekeltfoundation/docker-junebug#4]
I've built Python wheels of yowsup's dependencies and put them in our pypi repo. I think the only package you'll need to install is `libjpeg62`.

**Comment by hodgestar** [comment]
@JayH5 Do we have to do anything special to install from our pypi repo? And is there a way to test building images that access our pypi repo locally?

**Comment by hodgestar** [comment]
Do we want to have a pre-built Junebug too so we can avoid compiling its dependencies (e.g. cryptography)?

**Comment by hodgestar** [comment]
Maybe we can just install a pre-built vumi and then install Junebug on top of that?

**Comment by JayH5** [comment]
@hodgestar don't have to do anything special. It's set up in the base image (`export PIP_EXTRA_INDEX_URL="https://pypi.p16n.org/simple/"`).

All the Python things with build time dependencies that I've come across so far are in that repo. Other things are pulled from standard PyPi. If you want to see what's in the repo you can just `curl -L pypi.p16n.org/simple`. If you do a `pip wheel vumi`, pip will download Vumi + all dependencies and make them in to wheels. Only the wheels with `linux_x86_64` in the filename need to be stored in our PyPi as they are the only arch-specific things.

It's not a matter of having built versions of Vumi/Junebug as they don't directly use any native extensions -- they can still be pulled from standard PyPi. You can currently do `pip install vumi` from the `python-base` image and it should just install without needing any compilers or anything.

Unfortunately, pypi.p16n.org is manually maintained at the moment. I manually do a `pip wheel` in a `python:2` (big image with all the build deps but otherwise architecturally the same (Debian Jessie) as the `python:2-slim` image) container and then push the arch-specific wheels to our PyPi. 

I've been thinking about how to automate that. It's a problem because every time there's an update to a package (e.g. `psycopg2cffi` was updated, like, today I think) then the Docker image builds break.

**Comment by hodgestar** [comment]
Ah, cool.

The breakage is non ideal. Any thoughts on how to address that long term?

Short term, could I (or you?) rebuild the wheel for cryptography -- it seemed to be out of date when I built this (junebug) Docker image locally.

**Comment by JayH5** [comment]
@hodgestar: You can push to the PyPi with [this](https://github.com/praekelt/puppet/blob/develop/manifests/qa.pp#L345) username/password... I've actually already built the new version of cryptography just forgot to add to repo. Will do that now.

Longer term, I was thinking of building a hacky thing with a repo with a `requirements.txt` file in it with all the things we host and then having https://requires.io send in pull requests to keep it up to date. A few shell scripts + Docker could build the new wheels on Travis.

There are probably lots of other ways to do it.. that's just the best idea I've had so far.

**Comment by JayH5** [comment]
Done in #2
